README.md
package.json
samples/package.json

I will stage the release notes in the usual place, but it might be a little while (< an hour).

Version bump to 0.13.0

---

package.json
samples/package.json

This adds `v1p1beta1`.
Release notes being staged in the releases UI.

Bump version to 0.14.0

---

.mailmap
CONTRIBUTORS
package.json
protos/google/cloud/vision/v1/geometry.proto
protos/google/cloud/vision/v1/image_annotator.proto
protos/google/cloud/vision/v1/text_annotation.proto
protos/google/cloud/vision/v1/web_detection.proto
samples/package.json
src/v1/doc/google/cloud/vision/v1/doc_geometry.js
src/v1/doc/google/cloud/vision/v1/doc_image_annotator.js
src/v1/doc/google/cloud/vision/v1/doc_text_annotation.js
src/v1/doc/google/cloud/vision/v1/doc_web_detection.js
src/v1/doc/google/protobuf/doc_any.js
src/v1/doc/google/protobuf/doc_wrappers.js
src/v1/doc/google/rpc/doc_status.js
src/v1/doc/google/type/doc_color.js
src/v1/doc/google/type/doc_latlng.js
src/v1/image_annotator_client.js
src/v1/index.js
test/gapic-v1.js

New GAPIC code. Ready to release 0.15.0.

feat: update GAPIC generated code (v1), bump semver minor version

---

package.json
samples/package.json

Need to update dependencies to prevent security issues caused by dependent packages.

fix: releasing 0.15.2 with updated dependencies

---

samples/detect.v1p2beta1.js
samples/system-test/detect.test.js
samples/system-test/detect.v1p2beta1.test.js

Fixed the failing unit test.

---

samples/system-test/detect.test.js
samples/system-test/detect.v1p1beta1.test.js

Fixing the broken unit test

---

samples/system-test/detect.v1p1beta1.test.js

testing with the most reliable found entry.

---

package-lock.json
package.json
samples/package-lock.json
samples/package.json

bump version to 0.20.0

---

greenkeeper.json

Adds a greenkeeper.json to tell greenkeeper to update package dependencies in samples/ as well.

repo: setup greenkeeper.json to update dependencies in samples/package.json

---

package-lock.json
package.json
samples/package-lock.json
test/helpers.test.js

fix: update and cleanup dependencies

---

system-test/vision.js
test/helpers.test.js

deepEqual is deprecated. Use deepStrictEqual instead

chore: assert.deelEqual => assert.deepStrictEqual

---

samples/detect.js
samples/detect.v1p3beta1.js
samples/faceDetection.js
samples/textDetection.js

Updates region tags to be consistent with those in other languages and removes unused region tags

Vision region tag update

---

README.md
samples/README.md
samples/detect.js
samples/detect.v1p3beta1.js
samples/system-test/detect.test.js
samples/system-test/detect.v1p3beta1.test.js

[DO NOT MERGE] Vision GA – vision_localize_objects & vision_localize_object_gcs

---

CHANGELOG.md
package.json
samples/package.json

This pull request was generated using releasetool.

Release @google-cloud/vision v0.22.1

---

samples/automl/automlVisionDataset.js
samples/automl/automlVisionModel.js
samples/automl/automlVisionPredict.js

Project ID should be a string instead of number

Change the Project ID from number to string

---

samples/productSearch/importProductSets.v1p3beta1.js

Adding the tutorial import tags

Adding vision_product_search_tutorial_import tags

---

samples/productSearch/importProductSets.js
samples/productSearch/productSearch.js
samples/productSearch/productSets.js
samples/productSearch/products.js
samples/productSearch/referenceImages.js
samples/productSearch/similarProducts.js
samples/system-test/importProductSets.test.js
samples/system-test/productSearch.test.js
samples/system-test/productSets.test.js
samples/system-test/products.test.js
samples/system-test/referenceImages.test.js
samples/system-test/similarProducts.test.js

ProductSearch GA

---

src/helpers.js

docs: fix productSearch example

---

CHANGELOG.md
package.json
samples/package.json

This pull request was generated using releasetool.

Release @google-cloud/vision v0.24.0

---

samples/system-test/detect.v1p1beta1.test.js
samples/system-test/importProductSets.test.js

test: fix broken sample tests

---

samples/textDetection.js

docs: fix authentication url in textDetection.js sample file

---

src/index.ts

feat: export protos from src/index.ts

---

synth.py

fix: update synth.py

---

src/helpers.ts

fix: proper type for ImprovedRequest in manual layer

---

package.json
protos/google/cloud/vision/v1/image_annotator.proto
protos/google/cloud/vision/v1p1beta1/image_annotator.proto
protos/google/cloud/vision/v1p2beta1/image_annotator.proto
protos/google/cloud/vision/v1p3beta1/image_annotator.proto
protos/google/cloud/vision/v1p4beta1/image_annotator.proto
synth.metadata
synth.py

Run the latest version of the generator, update google-gax, update gts, and remove direct dependencies on eslint.

fix: remove eslint, update gax, fix generated protos, run the generator

---

package.json

fix: mocha tests
